In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [71]:
#Reading the data from the csv into feature and target array
df = pd.read_csv("Cancer_Data.csv")
type = {'M': 1,'B': 0}
df.diagnosis = [type[item] for item in df.diagnosis]
#print(df)
x_train = df.values[:, 2:32]
y_train = df.values[:,1]
y_train = np.reshape(y_train, (-1,1))
print(x_train)
l, w = x_train.shape
print(w)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
30


In [76]:
#Normalization
norm_l = tf.keras.layers.Normalization(axis=-1)
norm_l.adapt(x_train)
X_norm = norm_l(x_train)
Xt = np.tile(X_norm,(1000,1))
Yt= np.tile(y_train,(1000,1))   
print(Xt.shape, Yt.shape)   

(569000, 30) (569000, 1)


In [77]:
#Creating network architecture
tf.random.set_seed(1234)
model = Sequential (
    [
        tf.keras.Input(shape=(30,)),
        Dense(31, activation="sigmoid", name = "L1"),
        Dense(1, activation ="sigmoid", name = "L2")
        
    ]
)

In [78]:
#Checking initialized weights and biases
W1, b1 = model.get_layer("L1").get_weights()
W2, b2 = model.get_layer("L2").get_weights()
model.compile(
    loss = tf.keras.losses.BinaryCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),
)

model.fit(
    Xt , Yt,            
    epochs=10,
)

Epoch 1/10
17782/17782 [==============================] - 6s 342us/step - loss: 0.0034
Epoch 2/10
17782/17782 [==============================] - 6s 340us/step - loss: 2.1293e-08
Epoch 3/10
17782/17782 [==============================] - 6s 341us/step - loss: 1.1855e-09
Epoch 4/10
17782/17782 [==============================] - 6s 341us/step - loss: 9.0527e-10
Epoch 5/10
17782/17782 [==============================] - 6s 340us/step - loss: 8.5949e-10
Epoch 6/10
17782/17782 [==============================] - 6s 338us/step - loss: 8.3769e-10
Epoch 7/10
17782/17782 [==============================] - 6s 331us/step - loss: 8.2384e-10
Epoch 8/10
17782/17782 [==============================] - 6s 337us/step - loss: 8.1688e-10
Epoch 9/10
17782/17782 [==============================] - 6s 347us/step - loss: 8.1242e-10
Epoch 10/10
17782/17782 [==============================] - 6s 342us/step - loss: 8.0795e-10


In [79]:
#Checking fitted weights and biases
W1, b1 = model.get_layer("L1").get_weights()
W2, b2 = model.get_layer("L2").get_weights()
print(W1)

[[-4.28020209e-01  1.51127017e+00  6.67536497e-01 -2.44620395e+00
  -2.78882265e-01  1.25396466e+00  1.00392079e+00 -8.15982282e-01
   9.74307775e-01  3.93538743e-01  2.39306077e-01  1.82926152e-02
  -2.77536583e+00 -4.96162653e-01 -1.84823349e-01  1.64332831e+00
  -4.55234647e-02  1.29120362e+00 -6.35717988e-01 -3.06483191e-02
  -2.52142042e-01 -1.50641906e+00  1.75608003e+00  8.82683992e-02
  -3.03750634e+00 -3.01346689e-01 -2.07273602e-01 -3.87291491e-01
  -2.12743934e-02  6.57792315e-02  3.39388192e-01]
 [-8.18232954e-01  8.64838243e-01  1.26055622e+00 -1.29705191e+00
   7.07894340e-02  1.43162525e+00  1.79183531e+00 -8.72468889e-01
  -9.17808786e-02  1.07643330e+00  3.91409278e+00  9.81995702e-01
  -2.41320658e+00 -1.94327921e-01 -1.00869453e+00  1.15499246e+00
  -1.49183929e-01 -6.64742314e-04  3.94271553e-01  1.60184279e-01
   2.47294933e-01 -7.47952223e-01 -5.51889956e-01  3.94056201e+00
  -1.78946197e+00 -5.42526364e-01 -2.34094813e-01  3.52001905e-01
  -3.85561794e-01 -2.5879

In [94]:
#Checking Accuracy
predictions = model.predict(X_norm)
yhat = np.zeros_like(predictions)
count = 0
l,w = yhat.shape
for i in range(len(predictions)):
    if predictions[i] >= 0.5:
        yhat[i] = 1
    else:
        yhat[i] = 0

        
m = tf.keras.metrics.Accuracy()
m.update_state(y_train, yhat, sample_weight=None)
m.result()

18/18 [==============================] - 0s 557us/step


<tf.Tensor: shape=(), dtype=float32, numpy=1.0>